# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0f2ccf7ebc455bc39bf54e5ada19baf73365981c651ca61125c232738932ea94e592d2aa8a23d360ad62a8d01cf23e02c99e65d36bcefc667a29e63d068e702

test:
  secret_key_base: d48ee10319d2155010ccf82357ed97f01e31ff459634f53dfb4f460c898081ee18c6ea05ac50d9549c939fd653c4eb2d80c9157eea39eb87197b176ed90e201d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
